
project_id = "cotmtwabbkxrvbjygnwk"

# Staging configuration (add your staging project ID when available)
[staging]
project_id = ""  # Add your staging project ID here

[production]
project_id = "cotmtwabbkxrvbjygnwk"
