[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Secrets scanning configuration
[secrets]
  # Disable secrets scanning for specific paths
  scan_omit_paths = ["dist/**/*"]
  
  # Disable secrets scanning for specific keys
  scan_omit_keys = [
    "VITE_OPENAI_API_KEY",
    "VITE_SUPABASE_URL",
    "VITE_SUPABASE_ANON_KEY"
  ] 