
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cotmtwabbkxrvbjygnwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvdG10d2FiYmt4cnZianlnbndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyODk4MDgsImV4cCI6MjA1Mzg2NTgwOH0.o8dtLdlIC6jdU4O1d_7KDXAXP-DPkbINAz5mQ55haVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  // Add additional options to ensure proper handling of DB operations
  db: {
    schema: 'public',
  },
  global: {
    fetch: (...args) => fetch(...args),
  },
});
