
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cotmtwabbkxrvbjygnwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvdG10d2FiYmt4cnZianlnbndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyODk4MDgsImV4cCI6MjA1Mzg2NTgwOH0.o8dtLdlIC6jdU4O1d_7KDXAXP-DPkbINAz5mQ55haVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// This is the SQL that needs to be run on Supabase to create the collections table and RLS policies:

/*
-- Create collections table
CREATE TABLE IF NOT EXISTS public.collections (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- RLS policies
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;

-- Policy for selecting collections (users can only see their own collections)
CREATE POLICY "Users can view their own collections" 
  ON public.collections FOR SELECT 
  USING (auth.uid() = user_id);

-- Policy for inserting collections
CREATE POLICY "Users can insert their own collections" 
  ON public.collections FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- Policy for updating collections
CREATE POLICY "Users can update their own collections" 
  ON public.collections FOR UPDATE 
  USING (auth.uid() = user_id);

-- Policy for deleting collections
CREATE POLICY "Users can delete their own collections" 
  ON public.collections FOR DELETE 
  USING (auth.uid() = user_id);

-- Create indexes
CREATE INDEX IF NOT EXISTS collections_user_id_idx ON public.collections (user_id);
CREATE INDEX IF NOT EXISTS collections_position_idx ON public.collections (position);
*/
